language: node_js
node_js:
- '8'
# before_install:
#   - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
install:
  - cd app
  - yarn install
  - cd ..
  - cd data-api
  - yarn install
  - cd ..
script:
  - cd app
  - cd ..
  - cd data-api
notifications:
  slack: artsmia:XuPlydSpfoILZdCPIbOYQq59
  email: false
# services:
#   - mysql
