language: node_js
node_js:
  - "8"
install:
  - cd app && yarn install
  - cd server && yarn install && yarn run start-local
notifications:
    slack: artsmia:XuPlydSpfoILZdCPIbOYQq59
    email: false
