language: node_js
node_js:
  - "8"
install:
  - cd app && yarn install && cd ..
  - cd server && yarn install && yarn run start-test
notifications:
    slack: artsmia:XuPlydSpfoILZdCPIbOYQq59
    email: false
