language: node_js
node_js:
- '8'
# before_install:
#   - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
# install:
# - cd app
# - yarn install
# - yarn run start-local &
# - cd ..
# - cd server
# - yarn install
# - yarn run db-reset-test
# - yarn run start-test &
# - cd ..
notifications:
  slack: artsmia:XuPlydSpfoILZdCPIbOYQq59
  email: false
services:
  - mysql
